# Generated by Django 4.2.4 on 2023-09-03 00:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0002_alter_response_respauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='dateCreationn',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
